// Copyright 2013 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


// This file will be processed by the MIDL tool to produce the type library
// and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
  object,
  uuid(81379C6B-11EB-483D-A718-20FFB8F47534),
  dual,
  nonextensible,
  helpstring("IBrowserSwitcherBHO Interface"),
  pointer_default(unique)
]
interface IBrowserSwitcherBHO : IDispatch{ };

[
  uuid(092F5139-CCB8-4BB6-A0DD-F797A076490B),
  version(1.0),
  helpstring("BrowserSwitcher 1.0 Type Library")
]
library BrowserSwitcherLib
{
  importlib("stdole2.tlb");
  [
    uuid(B0D0378A-EBBA-4F5C-8D34-2BF358944267),
    helpstring("BrowserSwitcherBHO Class")
  ]
  coclass BrowserSwitcherBHO {
    [default] interface IBrowserSwitcherBHO;
  };
};
